# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0433\u0440\u0443\u043f\u043f\u044b')),
            ],
            options={
                'ordering': ('number',),
                'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430',
                'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b',
            },
        ),
        migrations.CreateModel(
            name='Students_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='\u0418\u043c\u044f')),
                ('last_name', models.CharField(max_length=200, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Student_group')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('formulation', models.TextField(verbose_name='\u0424\u043e\u0440\u043c\u0443\u043b\u0438\u0440\u043e\u0432\u043a\u0430')),
                ('order_in_course', models.IntegerField(verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0437\u0430\u0434\u0430\u043d\u0438\u044f')),
            ],
            options={
                'ordering': ('order_in_course',),
                'verbose_name': '\u0417\u0430\u0434\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0417\u0430\u0434\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Task_deadline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='\u0421\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Student_group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Task', verbose_name='\u0417\u0430\u0434\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('task', 'group'),
                'verbose_name': '\u0421\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438',
                'verbose_name_plural': '\u0421\u0440\u043e\u043a\u0438 \u0441\u0434\u0430\u0447\u0438',
            },
        ),
    ]
