# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_tasksubmission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskSubmission',
            new_name='Task_submission',
        ),
    ]
