# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 05:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_task_module_task_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='module_task_set',
        ),
    ]
