# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_remove_task_module_task_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduletaskset',
            name='formulation',
        ),
        migrations.AddField(
            model_name='task',
            name='module_task_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contest.ModuleTaskSet', verbose_name='\u0417\u0430\u0434\u0430\u043d\u0438\u0435'),
        ),
    ]
