# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_auto_20170815_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_deadline',
            name='deadline_type',
            field=models.IntegerField(choices=[(0, '\u041f\u0435\u0440\u0432\u044b\u0439 \u0441\u0440\u043e\u043a'), (1, '\u0412\u0442\u043e\u0440\u043e\u0439 \u0441\u0440\u043e\u043a')], default='1', verbose_name='\u0412\u0438\u0434 \u0441\u0440\u043e\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task_submission',
            name='evaluation',
            field=models.PositiveIntegerField(blank=True, default=None, verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430'),
        ),
    ]
