# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_professor_profile_submissiongrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiongrade',
            name='grade',
            field=models.PositiveIntegerField(default=0, verbose_name='\u041e\u0446\u0435\u043d\u043a\u0430'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submissiongrade',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Professor_profile', verbose_name='\u041f\u0440\u0435\u043f\u043e\u0434\u0430\u0432\u0430\u0442\u0435\u043b\u044c'),
        ),
    ]
