# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 06:31
from __future__ import unicode_literals

from django.db import migrations, models

from datetime import datetime
class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_auto_20170827_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_submission',
            name='subm_time',
            field=models.DateTimeField(default=datetime(2017, 8, 30, 9, 33, 46, 393672), verbose_name='\u0412\u0440\u0435\u043c\u044f \u043e\u0442\u043f\u0440\u0430\u0432\u043a\u0438'),
            preserve_default=False,
        ),
    ]
