# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 07:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contest', '0015_task_submission_subm_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor_profile',
            name='system_user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
