# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-02 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_professor_profile_system_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_deadline_first',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='\u0421\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Student_group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ModuleTaskSet', verbose_name='\u0417\u0430\u0434\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('task', 'group'),
                'verbose_name': '\u041f\u0435\u0440\u0432\u044b\u0439 \u0441\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438',
                'verbose_name_plural': '\u041f\u0435\u0440\u0432\u044b\u0435 \u0441\u0440\u043e\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Task_deadline_last',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='\u0421\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.Student_group', verbose_name='\u0413\u0440\u0443\u043f\u043f\u0430')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.ModuleTaskSet', verbose_name='\u0417\u0430\u0434\u0430\u043d\u0438\u0435')),
            ],
            options={
                'ordering': ('task', 'group'),
                'verbose_name': '\u0412\u0442\u043e\u0440\u043e\u0439 \u0441\u0440\u043e\u043a \u0441\u0434\u0430\u0447\u0438',
                'verbose_name_plural': '\u0412\u0442\u043e\u0440\u044b\u0435 \u0441\u0440\u043e\u043a\u0438',
            },
        ),
        migrations.RemoveField(
            model_name='task_deadline',
            name='group',
        ),
        migrations.RemoveField(
            model_name='task_deadline',
            name='task',
        ),
        migrations.AddField(
            model_name='professor_profile',
            name='patronymic',
            field=models.CharField(default='\u0418\u0432\u0435\u0440\u0438\u0435\u0432\u0438\u0447', max_length=200, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students_profile',
            name='patronymic',
            field=models.CharField(default='\u0418\u0432\u0430\u043d\u043e\u0432\u0438\u0447', max_length=200, verbose_name='\u0424\u0430\u043c\u0438\u043b\u0438\u044f'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Task_deadline',
        ),
    ]
