# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-26 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_auto_20170902_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student_group',
            options={'ordering': ('title',), 'verbose_name': '\u0413\u0440\u0443\u043f\u043f\u0430', 'verbose_name_plural': '\u0413\u0440\u0443\u043f\u043f\u044b'},
        ),
        migrations.RemoveField(
            model_name='student_group',
            name='number',
        ),
        migrations.AddField(
            model_name='student_group',
            name='title',
            field=models.CharField(default='\u041f\u043e\u043d\u0435\u0434\u0435\u043b\u044c\u043d\u0438\u0435 14:30', max_length=200, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0433\u0440\u0443\u043f\u043f\u044b'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='professor_profile',
            name='patronymic',
            field=models.CharField(max_length=200, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
        migrations.AlterField(
            model_name='students_profile',
            name='patronymic',
            field=models.CharField(max_length=200, verbose_name='\u041e\u0442\u0447\u0435\u0441\u0442\u0432\u043e'),
        ),
    ]
